### PR TITLE
Add Travis CI configuration

### PR DESCRIPTION
**Pull request by axmat**

### CODE REVIEW

**Comment by axmat** [comment]
@9il if you could review this, it would be appreciated.

**Comment by 9il** [comment]
cool, don't forget to fix outdated code and make Travis green

**Comment by 9il** [comment]
mir-neural is very outdated. It needs to be updated with the latest mir-algorithm and other packages. Also, it needs an update for newer compilers.

**Comment by axmat** [comment]
I am working on it.

**Pull request closed without merging**
